# Generated by Django 3.1.5 on 2021-09-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='social',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
